### ISSUE TITLE
2019.07.16 lab meeting discussion

### ISSUE THREAD

**Issue by JiseungHong** [kaist-cp/hafnium-verification#1]
@jeehoonkang @efenniht 

* cpu.c stack_bottom 초기화 이후 사용이 없음
* gerrit에서 api_vcpu_prepare_run 바뀐 것 읽기
* C 코드를 먼저 refactor -> Rust
* cpu/vm 의 public interface를 정리해서 field 접근을 method call로 바꾸기 (ex. interrupts)

**Comment by efenniht** [comment]
C 코드를 먼저 refactor 하는 것 대신, 먼저 Rust로 C 코드를 거의 그대로 옮긴 다음 Rust 코드를 refactor하기로 했습니다.

**Comment by efenniht** [comment]
gerrit의 해당 PR: https://hafnium-review.googlesource.com/c/hafnium/+/5600

**Comment by jeehoonkang** [comment]
- 개별 action item별로 issue 만들기를 권장합니다.
- 제가 할 action이 아니라 :) 저는 assignee에서 빼겠습니다.
- 진전이 있으면 PR 날리거나 아니면 다른 방법으로 제게 알려주세요~
