### ISSUE TITLE
Resolve race condition in `dlog`

### ISSUE THREAD

**Issue by efenniht** [kaist-cp/hafnium-verification#14]
현재 C 코드와 Rust 코드 모두에 `dlog`가 정의되어 있고, 두 코드가 잡는 락은 서로 다릅니다. `dlog.c` 의 `lock()` 및 `unlock()` 함수가 `dlog.rs` 의 `WRITER` 내부 락을 잡도록 해야 합니다.

**Comment by efenniht** [comment]
장기적으로는 C의 `dlog`를 없애야 하는 데 워낙 많은 테스트 코드가 `dlog`를 사용해서 없앨 수 있을 지 모르겠네요. :cry:

**Comment by jeehoonkang** [comment]
- C의 dlog는 안없애는게 맞을 거 같습니다.
- 락만 통일하면 될듯 합니다.  Rust에 있는 락만 쓰면 될거같아요.

**Comment by jeehoonkang** [comment]
C의 dlog 구현을, Rust 구현을 바로 호출하는 식으로 구현하는게 좋을 것 같습니다.
