### ISSUE TITLE
Kernel driver load test failed

### ISSUE THREAD

**Issue by efenniht** [kaist-cp/hafnium-verification#2]
`./kokoro/ubuntu/test.sh` 를 실행했을 때 다음과 같이 실패합니다.

```
+ timeout --foreground 30s ./test/hftest/hftest.py --out out/reference/qemu_aarch64_clang --out_initrd out/reference/qemu_aarch64_vm_clang --log out/reference/kokoro_log hafnium --initrd test/linux/linux_test --vm_args 'rdinit=/test_binary --'
Logs saved under out/reference/kokoro_log/hafnium_test/linux/linux_test
    SUITE linux
      RUN load_hafnium
[x]     FAIL -- out/reference/kokoro_log/hafnium_test/linux/linux_test/linux.load_hafnium.log
[x] FAIL: 1 of 1 tests failed
```
저장된 로그 (`linux.load_hafnium.log`) 의 내용은 다음과 같습니다.
```
...
[    4.977172] Run /test_binary as init process
[    5.002601] hafnium: version magic '4.19.13 SMP preempt mod_unload aarch64' should be '4.19.13-gbbc0e19a SMP preempt mod_unload aarch64'
[hftest] Failure: ../../test/linux/linux.c:42
[hftest]     finit_module(module_file, "", 0) == 0 (finit_module(module_file, "", 0)=-1, 0=0)
[hftest] Failure: ../../test/linux/linux.c:48
[hftest]     delete_module("hafnium", 0) == 0 (delete_module("hafnium", 0)=-1, 0=0)
[hftest] FAIL
[    5.028979] reboot: Power down
```

테스트 환경은 다음과 같습니다: Ubuntu 16.04.11, gcc 5.4.0, rustc 1.37.0.
테스트한 버전은 현재 HEAD인 9f5e5022f3b3df571d1c782684a017d051103a3a 입니다.

**Comment by jeehoonkang** [comment]
- Upstream에서도 fail 하는지 확인해보세요 (https://hafnium.googlesource.com/hafnium)
- 만일 upstream에서는 fail하지 않는다면, upstream commit을 merge해보세요.
- 그래도 fail이 지속된다면, 다시 연락주시기 부탁드립니다.

**Comment by efenniht** [comment]
- upstream에서 테스트했을 때는 성공했습니다. 
 - 그런데 upstream 전체를 머지해서 빌드하려고 하니 `mm_lock_stage1` 류의 함수가 필요해서 빌드에 실패합니다. (upstream 의 `mm.c` 가 `mm.rs`로 대체되었으므로)
 - 한편 지금의 `mm.rs` 구현에서는 하이퍼바이저 페이지 테이블이 `SpinLock` 으로 감싸져 있어서 `mm_lock_stage1` 함수의 rust 버전을 쉽게 만들 수 없을 것 같습니다.

**Comment by jeehoonkang** [comment]
- 일단 먼저 upstream patch를 rust port로 가져오는게 좋겠습니다.
- `mm_lock_stage1`을 Rust 버전으로 만들기 어려운 이유를 좀더 자세히 이해하고 싶습니다.  제 생각엔 쉽게 구현할 수 있지 않을까 싶어서리...

필요하면 내일 offline으로 만나서 잠깐 얘기해보죠

**Comment by efenniht** [comment]
어렵다기보다는, `mm_lock_stage1` 과 `mm_unlock_stage1` 함수를 분리해서 만들어야 하므로 `SpinLock` 내부의 `lock`을 public하게 만들거나 `RawSpinLock`을 따로 사용하도록 `mm.rs` 를 바꾸어야 한다는 이유였습니다.

**Comment by jeehoonkang** [comment]
- 일단 `lock`을 public하게 만들어서 해보죠...
- 나중에는 리팩토링을 잘 해서 mm_lock_stage1, mm_unlock_stage1을 사용하지 않게 되리라 생각합니다.

**Comment by efenniht** [comment]
- upstream commit log 를 살펴보았는데, https://hafnium.googlesource.com/hafnium/+/3c0a90a9be8d5d86c84b158997b6ba3483da8f9a 이 커밋이 `mm_*` 류 함수가 lock 을 인자로 가지도록 수정한 커밋입니다.
 - 수정한 내역이 lock에 의해 특별히 다른 의미를 가지게 된 것이 아니므로, 제 생각에는 그냥 새로운 `RawSpinLock` 을 하나 만들어서 이것을 lock/unlock하는 함수로 `mm_lock_stage1` 과 `mm_unlock_stage1` 을 구현해도 될 것 같습니다.
 - 지금의 `HYPERVISOR_PAGE_TABLE` 내부 락을 접근하는 방법은 기존 Rust 코드와 더 충돌이 일어날 것 같습니다.
 - 새로운 락을 만들면  critical region에서 다시 락을 거므로 조금 비효율적인 코드가 되지만, 실행에는 문제 없지 않을까요?
 - 그렇게 해 보고 테스트한 다음 결과를 알려드리겠습니다.

**Comment by jeehoonkang** [comment]
저는 최대한 기존 코드의 의도를 수정하지 않는 선에서 Rust로 포팅되면 좋겠습니다.  그런 이유로 lock을 하나 더 거는건 왠지 느낌이 꺼림칙한데, 일단 kaist-cp로 PR 날려봐주시면 같이 코드리뷰해볼 수 있겠습니다.

**Comment by efenniht** [comment]
일단 PR #3 을 보냈습니다!
