### ISSUE TITLE
Which data structures can we modify their layout?

### ISSUE THREAD

**Issue by efenniht** [kaist-cp/hafnium-verification#21]
많은 구조체들이 C 코드에서 사용되고 있으므로, 자료구조를 뜯어고치기 전에 무엇이 어디에서 사용되는 지 조사해야 합니다.

**Comment by efenniht** [comment]
### `vcpu` 의 멤버에 접근하는 코드
 - `src/arch/aarch64/hypervisor/{handler, psci_handler}.c`: `regs`, `vm` 등
 - `src/main.c`: `regs`, `vm`, `cpu`

### `vcpu_locked`를 사용하는 코드
 - `src/arch/aarch64/hypervisor/psci_handler.c`
 - `src/load.c`

### `cpu` 의 멤버에 접근하는 코드
 - `src/arch/aarch64/hypervisor/psci_handler.c`: `lock`, `is_on` 등
 - `src/arch/aarch64/hypervisor/offset.h`: `cpu_entry` 등에 사용됩니다.
 - `src/cpu.c`: 옮기지 않은 `cpus` 초기화 코드

### `vm`의 멤버에 접근하는 코드
 - `src/arch/aarch64/hypervisor/psci_handler.c`: `vcpu_count`, `id`
 - `src/load.c`: `id`, `ptable`

### `vm_locked` ....

**Comment by jeehoonkang** [comment]
- `*_locked`: 타입을 Rust로 옮겼으니 괜찮지 않을까?
- (옮길 코드) `main.c`는 어차피 Rust로 옮길 것...
- (안옮길 코드) 예컨대 `{handler, psci_handler}.c`에서 regs에 접근한다면, `Regs` 타입의 메서드를 호출하는 방식이어야 할 것...

**Comment by efenniht** [comment]
메서드를 호출하는 방법으로 만들면, `vcpu`의 배치가 달라져도 항상 동일하게 접근할 수 있습니다!
다만, `struct vcpu`의 크기가 달라지는 것 또한 추적해야 하는데요, `struct vm`이 유일하게 포인터가 아닌
`stuct vcpu` 자체를 멤버로 가집니다. `struct vm`을 멤버로 가지는 구조는 없으니 `vm`의 멤버에 접근하는 부분만 바꾸면 됩니다.

그래서 해야할 일 정리:
 - `{vcpu, cpu, vm}` 멤버에 접근하는 코드 `{vcpu, cpu, vm}_get_xxx` 따위로 바꾸기
 - `{cpu, vm}.h` 에서 `vcpu` 와 `vm` 정의 삭제하고 `struct vcpu;` 따위로 타입만 알림
 - `cpu` 도 마찬가지로 하고싶지만, 아직 초기화 코드가 남아 있으므로 얘는 구조가 바뀔 때마다 헤더를 바꾸도록 하기
 - `*_locked` 타입은 Rust에서 이제 lockguard를 사용하도록 수정하기

**Comment by efenniht** [comment]
`src/arch/aarch64/hypervisor/offset.c` 에서, 어셈블리 코드에서 사용하는 상수(구조체 필드의 오프셋)들이 실제로 정의와 일치하는 지 검사하는데요, 이 코드를 `const_assert_eq` 매크로를 사용하여 Rust로 포팅하려 했더니 internal mutability가 존재하는 `VCpu`는 constant expression에서 생성할 수 없다고 합니다. ㅠㅠ 그래서 대안으로,
 - `offset.c` 를 놔 두고, 그러기 위해서 `VCpu`가 바뀔 때마다 `struct vcpu`도 바꿉니다. 또는,
 - `const_assert_eq` 대신 `cpu_module_init`이 실행될 때 이 assert 문을 검사하도록 합니다.

일단 후자의 방법으로 해보도록 하겠습니다.

**Comment by efenniht** [comment]
`vm_get_xx` 류의 함수들은 LTO를 사용하지 않으면 느릴 것입니다...
