### ISSUE TITLE
Preparing poster session in SIGPL summer school

### ISSUE THREAD

**Issue by efenniht** [kaist-cp/hafnium-verification#24]
포스터에 들어갈 내용을 구상해 보았습니다:

# 하이퍼바이저 검증의 첫 단추로 Rust로 포팅하기

## Introduction

거대한 소프트웨어를 검증하는 것은 어렵습니다.

특히나 아직 정확한 spec이 정해지지 않은 프로그램은 더 그렇습니다.

하이퍼바이저는 거대하고, 거의 어디서나 concurrency를 고려하면서 작성되었습니다.

이 프로그램의 검증을 (memory and concurrency)-safe programming language의 도움을 받아, 많은 부분을 자동화할 수 있다면 어떨까요?

Rust로 포팅하면서 얻을 수 있는 것은 다음과 같습니다.

- Rusty하게 포팅하는 것은 C 코드의 리팩토링이며, 잠재적인 버그를 잡고 더 개선된 자료구조를 만드는 데 도움이 됩니다.

- Safe Rust code는 타입체커에 의해서 concurrent 상황에서의 메모리 안전성이 보장됩니다.
- 이 타입체커가 보장하는 내용은 RustBelt를 통해서 Coq으로 뽑아낼 수 있습니다.
- 궁극적인 스펙을 만드는 데에 도움이 됩니다?

## Hypervisor: Hafnium

Google에서 주도적으로 작성 중인 Android용 하이퍼바이저입니다.

기존의 TrustedZone 에 한계를 느껴서 만들기 시작했습니다.

코드의 대부분은 C로 작성되었습니다.

스케쥴링과 각종 복잡한 임무는 (primary VM) 커널에게 맡기고, isolation만을 지원하는 것을 목표로 합니다.

## Safe PL: Rust

Mozilla Research 에서 시작된 시스템 프로그래밍 언어입니다.

Memory safety와 safe concurrency를 주요 목표로 두고 디자인되었습니다.

ownership과 borrowing을 통해서 안전성을 보장합니다.

RustBelt를 통해서 Coq으로 뽑아낼 수 있습니다?

그 외에도 rich type system이

- memory safety 이외의 safety를 타입으로 보장할 수 있도록 합니다.
- abstract structure에 더 가깝게 디자인할 수 있으므로, spec을 만드는 것에 도움을 줍니다.

## What we've done

- memory management를 담당하는 코드를 Rusty 하게 포팅했습니다.
  - 그러면서 버그도 찾았습니다.
- 외부 API와 virtual components 를 담당하는 코드를 포팅 중입니다.

**Comment by jeehoonkang** [comment]
Introduction을 CGI에 맞춰 재구성해주시길 부탁드립니다:

- Context: 문제를 설명하기 위한 배경.  우리로선 Project Oak의 일부로서 Hafnium verificaiton에 대한 이야기가 되겠네요.  빅 데이타의 시대에 보안이 점점 중요해지고 그래서 secure IoT & server platform을 만들거고 ... 등등 이런 큰 이야기부터 시작해서 Hafnium verification까지 좁혀나가면 될 것 같습니다.

- Gap: 문제.  우리로선 검증 비용이 너무 크다는게 되겠습니다.

- Innovation: 해결.  우리로선 Rust로 포팅함으로써 어쩌구 저쩌구... 가 되겠습니다.  여기서 Rust 설명도 나와도 되고, 아님 다음 section으로 미뤄도 괜찮습니다.


우리가 preliminary result를 가지고 이야기하는 것이므로, "introduction"이라는 section 대신에 "Context", "Problem", "Approach", "Preliminary Results" 정도로 section을 줘도 괜찮을 것 같아요.  제목 뒤에 "Context: The Need for Secure Data Processing" 와 같이 부제를 줘도 되구요.

**Comment by efenniht** [comment]
바꾸어 보았습니다:

# 하이퍼바이저 검증의 첫 단추로 Rust로 포팅하기

## Context

지금은 바야흐로 IoT의 시대.

손톱만한 프로세서가 사람들의 private data를 처리하고 있습니다.

안전하면서도 embedded 에 걸맞게 cost-effective 한 secure platform을 어떻게 제공할 수 있을까요?

ARM은 secure/normal world의 isolation을 통해서 알려지지 않은 보안 결함으로부터 private data를 보호할 수 있는 TrustZone이라는 기술을 만들었습니다.

TrustZone은 하지만, 여러 가지 한계가 있습니다.

- TrustZone에 소프트웨어를 작성할 수 있는 사람은 device manufacturers와 그의 허가를 받은 사람들로 한정됩니다.
- Secure world에서 사용할 수 있는 자원은 하드웨어 스펙으로 제한되어 있습니다.

그래서 Google은 소프트웨어 사이의 isolation을 제공하는 프로그램을 만드려고 하고, 그것이 Hafnium입니다.

Hafnium 은 stage-1 hypervisor로 primary VM (normal world) 와 secondary VMs (secure worlds) 를 isolation합니다.

## Problem

그런데 Hafnium은 작지 않은 크기의 소프트웨어입니다. (Lines of C code = about 5000)

이 프로그램은 아직 개발 중이고 고정된 spec 또한 만들어지지 않았습니다.

이런 프로그램을 검증하는 것은 시간과 인력을 많이 소모하는 일입니다.

어떻게 하면 효율적으로 검증할 수 있을까요?

## Approach

우리의 아이디어는, 이 프로그램의 검증을 safe system programming language의 도움을 받아 많은 부분을 자동화할 수 있다는 것입니다.

우리는 이 아이디어를 바탕으로, Hafnium을 Rust로 포팅하고 있습니다. 이를 통해 기대하는 것은 다음과 같습니다.

- Safe Rust code는 타입 체커에 의해서 concurrent 상황에서의 메모리 안전성이 보장됩니다.
- 이 타입 체커가 보장하는 내용은 RustBelt와 같은 도구를 통해서 Coq으로 뽑아낼 수 있습니다.
- Safe Rust로 포팅하는 것은 C 코드의 리팩토링이며, 잠재적인 버그를 잡고 더 개선된 자료구조를 만드는 데 도움이 됩니다.
- Unsafe한 부분을 분리해 내면서, Hafnium의 스펙에 들어가야 하는 주요한 기능과 한계점을 알아낼 수 있습니다.



## Preliminary Results

- 포팅의 진전 상황
  - By lines
    - Original Hafnium에는 Arch-independent한 C 코드가 3578줄 있습니다. (19.8.20 기준)
    - 현재 포팅 중인 코드에는 Arch-independent한 C 코드가 1446줄 있습니다.
    - Rust 코드는 3524줄입니다.
  - memory management을 담당하는 코드를 Rusty하게 포팅했습니다.
  - 외부 API와 virtual components (VCPU, VM)을 담당하는 코드를 Rust로 작성했으며, safe하고 Rusty하게 리팩토링 중입니다.
- 포팅을 통한 버그 찾기
  - Concurrency-related bugs
    - 알맞은 락을 걸지 않고 데이터에 접근하는 버그를 2개 찾았습니다.
  - Other general bugs
    - 로직이 잘못 된 버그를 하나 찾았습니다.
- Unsafe 코드를 통해서 스펙의 청사진 그리기
  - 예시) vcpu들은 vm의 page table에 대한 알맞은 borrowing 없이 raw pointer를 저장합니다. 따라서 vcpu들은 자신들이 가지고 있는 페이지 테이블이 원치 않게 변경될 수 있으며, Hafnium의 스펙에서 언제 그런 일이 발생할 수 있는 지 명시해야 합니다.

**Comment by efenniht** [comment]
포스터를 발표하고 나서 느낀 점입니다 (반말로 작성됨)

- Approach가 좀 불명확하다.

  - 내가 잘 이해를 못해서 인 점도 있음

    - verification을 그래서 결국 어떻게 할 것인가? 에 대한 큰 그림을 그려 주는 것이 중요하다. 사람들도 그게 없어서 혼란스러워 했다. 사실 근데 그걸 나도 저번 주 금요일에 알았어...
    - Rust 코드에서 어떻게 정보를 뽑아내는데? Concurrent Separation Logic이 어쩌구 저쩌구 말은 했는데 아직도 디테일은 모르겠음. 일단 자동화가 없다는 부분은 다행히 아무도 안 물어봄.

  - C에서 Rust로 간 다음 Rust를 verify하는 것으로 착각하는 분들이 많다. 나도 사실 처음엔 그런 줄 알았다. 애초에 그런 건 아직 없다. 이 검증의 경로를 잘 드러내야 한다.

  - 그래서 그림이 좀 별로라는 생각이 든다.

    - 예제는 나쁘지는 않았는데 (잘 써먹음) 이것보다 더 중요한 그림이 많음

    - 검증의 workflow. 일단 C -> unsafe Rust -> idiomatic Rust -> Logic

    - 그리고 삼각형 모양으로

      ```
      c ------verify------> logic
       \port          analyze/
        \---> Rust --------/
      ```

      대충 이런 식으로. 어디가 자동화되는 지 (verify 파트) 그리고 왜 포팅이 semantics를 보존하지 않아도 verification 이 깨지지 않는 지 말해야 함. 이 포팅은 cost를 줄이기 위한 작업이라는 것!

  - 어떤 분이 static analysis + SAT solver 등을 이용해서 분석하는 것이 어떤 지 여쭈어 보셨다. 허충길 교수님께서 저번 주 금요일에 말씀하신 내용을 거의 그대로 인용함. 'SAT solver는 trustbase가 너무 커져서 좀 불안정해진다.'

  - 다른 분은 Rust에서 이것보다 더 좋은 정보를 뽑아낼 수 없을까에 대해서 여쭤보셨는데 이건 내가 제대로 이해를 못해서 답을 못함.

  - Rust에 대해서 잘 모르심

    - ownership and borrowing. 이 컨셉을 거의 계속 설명함.
    - `unsafe` block의 존재. 이걸 안다고 가정하고 설명을 적어서 약간 헷갈리시는 분들이 많았음. 사실 Unsafe-free Rust code is memory-safe 라고 문장을 적으려다가 말았는데 잘 돌려서 말하려면 "통상적인" Rust code is memory-safe 가 그나마 적당하다. common이 여기에 맞나?

- "a First Step of Verification" 이 맞나?

  - 포팅한 Rust를 검증한다는 다수의 착각이 이 제목 때문에 발생한 것은 아닐까?
  - 난 pre-stage of verification 또는 preparation step of verification 같은 게 더 맞다고 생각한다. 실제 검증 전에 이 작업을 optimize 하는 것이니까?
  - 결국 검증 = well-typed Coq proof를 만드는 것인데 실제로 proof는 어디서도 생성되지 않는다. ㅜㅜ
