### ISSUE TITLE
`enable_and_pending_count` is not locked but accessed

### ISSUE THREAD

**Issue by efenniht** [kaist-cp/hafnium-verification#26]
`Interrupts` 의 `enable_and_pending_count`에 접근하는 코드 중 몇몇은 `interrupt_lock`을 걸지 않습니다.

- `api_vcpu_prepare_run` -> PR #22 이후 `cpu.lock` 이 `cpu.execution_lock` 으로 그냥 대체되었음
 - `api_spci_msg_recv` -> 이전부터 락을 안 걸고 사용했음

전자는 #22 가 잘못된 것이고 후자는 원래 Hafnium의 버그입니다. 와! 버그를 찾았어요!

**Comment by efenniht** [comment]
Hafnium mailing list에 리포팅하기. 가입이 승인이 되는 대로 할 예정입니다.

**Comment by jeehoonkang** [comment]
https://github.com/kaist-cp/hafnium-verification/blob/hfo2/hfo2/src/api.rs#L1120 이 라인일 것으로 예상하는데, 맞죠?  리포팅 합시다 :)

**Comment by hkim15** [comment]
와!!! Rust의 type system이 이 bug를 찾는데 도움이 됐나요?

**Comment by efenniht** [comment]
@hkim15: 네. `interrupts`를 `SpinLock<Interrupts>` 타입으로 바꾸면서 이 field에 접근하는 코드를 바꾸고 있었는데, `api_spci_msg_recv`에서는 마땅히 락을 거는 곳이 없어서 알게 되었습니다.

**Comment by hkim15** [comment]
혹시 최신 Hafnium code에도 같은 문제가 있는지 확인해 보셨어요?
https://hafnium.googlesource.com/hafnium/

**Comment by efenniht** [comment]
넵. 해당 함수 내에 `current` vcpu에 대한 락을 거는 코드가 없고, `enable_and_pending_count` 변수를 수정하는 다른 함수들은 vcpu의 lock 을 항상 거는 것으로 보아 문제는 아직 있는 것으로 생각됩니다.

**Comment by efenniht** [comment]
메일링 리스트에 리포트했습니다: https://groups.google.com/forum/#!topic/hafnium-discuss/4-WFYp9WXAY
