### ISSUE TITLE
Refactor `api_init`

### ISSUE THREAD

**Issue by efenniht** [kaist-cp/hafnium-verification#31]
`api_init` 이 함수는 `one_time_init` 함수에서 단 한 번 호출되며, `one_time_init`은 자신의 `ppool`을 `api_init`에게 주고 더 이상 사용하지 않습니다. 따라서 `ppool`의 레퍼런스를 받아 `new_from` 함수를 호출하기보다는 `ppool`을 그대로 받아서 초기화해도 됩니다.

**Comment by jeehoonkang** [comment]
`main.c`를 포팅하는 작업이 선행되어야 할 것으로 보입니다 (#32)

**Comment by jeehoonkang** [comment]
#35 에서 해결하겠습니다.
