### ISSUE TITLE
unsafe 양을 측정?

### ISSUE THREAD

**Issue by jeehoonkang** [kaist-cp/hafnium-verification#33]
정량화를 위해..

**Comment by efenniht** [comment]
https://github.com/icefoxen/cargo-osha 요런 툴이 있습니다 :)

**Comment by efenniht** [comment]
이 툴을 실행한 결과는 다음과 같습니다. (대상은 `src/*.rs`로, arch-independent한 것만 조사했습니다.)
```
Unsafe functions: 113/151
Unsafe expressions: 338/3267
Unsafe traits: 0/3
Unsafe methods: 35/171
Unsafe impls: 5/61
```

**Comment by efenniht** [comment]
정정합니다. PR #27 직후를 기준으로,
```
Unsafe functions: 113/149
Unsafe expressions: 335/3334
Unsafe traits: 0/3
Unsafe methods: 34/164
Unsafe impls: 5/59
```

**Comment by jeehoonkang** [comment]
- 이걸 돌리는 script를 만들어서 repo에 포함시키면 좋겠습니다.
- 스크립트 실행하는 법도 hfo2/README.md 에 업데이트 해주세요.

**Comment by jeehoonkang** [comment]
@efenniht ping 이 스크립트 설치/실행법만 알려주시면 감사하겠습니다..!

**Comment by efenniht** [comment]
확인해 보았는데 사용하기 좀 더 쉬운 툴로 https://github.com/anderejd/cargo-geiger 가 있습니다. `cargo install cargo-geiger` 한 다음 `cargo geiger`로 실행하면 된다고 합니다.

**Comment by jeehoonkang** [comment]
`cargo-geiger`는 전체 개수를 알려주진 않네요..  비율로 말하면 좋을 것 같아서 unsafe/전체 둘다 알 수 있음 좋겠습니다.

**Comment by efenniht** [comment]
전체 비율은 cargo-osha를 사용해야 할 것 같습니다. 스크립트 실행법을 추가해 놓도록 하겠습니다.

**Comment by efenniht** [comment]
Closes by 28f5638ceeae2e2f952d6a5566e77bd90ef4c788

**Comment by efenniht** [comment]
`cargo-count`라는 툴이 더 사용하기 쉽고 비교에도 좋은 LOC 비율을 알려줍니다. d7722461b950ea9f228111b99dee14aca940eb57
