### ISSUE TITLE
TwoVmLocked 왜 필요한가요?

### ISSUE THREAD

**Issue by jeehoonkang** [kaist-cp/hafnium-verification#42]
저거랑 vm_lock_both가 사용되는 곳이 없는 것 같아서...

**Comment by efenniht** [comment]
네. 저도 확인해 보니 사용되는 곳이 없네요. 없애도록 하겠습니다.

**Comment by efenniht** [comment]
없앴습니다 (99cbd022690bf8d05d118f2dc789d9c1f1ca2400)
