### ISSUE TITLE
INITED에 대하여

### ISSUE THREAD

**Issue by efenniht** [kaist-cp/hafnium-verification#55]
지금의 코드는 모든 cpu가 `INITED`의 값을 검사하고 따라서 AtomicBool로 바꾸었습니다. (a12d91dc39da2182afdbde75fed9a52b42cb52de) 그런데 원래 hafnium 코드를 확인해 보니까 이런 식으로 작성되어 있습니다.

```c
static volatile bool INITED = false;
if (cpu_index(c) == 0 && !INITED) {
    one_time_init();
    INITED = true;
}
...
```

이 경우에는 `INITED` 를 읽는 CPU가 항상 하나이므로 `INITED`를 atomic하게 접근하지 않아도 됩니다. 본래의 hafnium 구현대로 만드는 게 맞지 않을까요?

**Comment by jeehoonkang** [comment]
@efenniht 네..  한 CPU에서만 접근하므로 nonatomic인게 맞는 것 같긴 합니다.  Volatile이 왜 필요한진 잘은 모르겠습니다만 C Hafnium 의도대로 따라가고 주석만 남기는게 어떨까 합니다.
