### ISSUE TITLE
c2rust 돌려보기

### ISSUE THREAD

**Issue by jeehoonkang** [kaist-cp/hafnium-verification#62]
얼마나 잘 나오는지...

https://c2rust.com/

**Comment by efenniht** [comment]
지원하지 않는 implicit cast 때문에 실패합니다.

```
In file included from ../../test/arch/mm_test.c:17:
In file included from ../../inc/hf/mm.h:26:
In file included from ../../inc/hf/mpool.h:22:
In file included from ../../inc/hf/spinlock.h:19:
/home/efenniht/repos/hafnium/prebuilts/linux-x64/clang/lib64/clang/8.0.4/include/stdatomic.h:370:10: warn
ing: c2rust: Encountered unsupported atomic expression
        return (atomic_exchange_explicit(&__object->__flag, 1, __order));
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
```
../../test/arch/mm_test.c:47:2: warning: c2rust: Encountered unsupported generic selection expression
        ASSERT_TRUE(arch_mm_is_block_allowed(0));
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../test/hftest/inc/hftest.h:53:24: note: expanded from macro 'ASSERT_TRUE'
#define ASSERT_TRUE(x) ASSERT_EQ(x, true)
                       ^~~~~~~~~~~~~~~~~
../../test/hftest/inc/hftest.h:46:25: note: expanded from macro 'ASSERT_EQ'
#define ASSERT_EQ(x, y) HFTEST_ASSERT_OP(x, y, ==, true)
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../test/hftest/inc/hftest_impl.h:242:3: note: expanded from macro 'HFTEST_ASSERT_OP'
                hftest_any_get(lhs_value, lhs) = (lhs);                    \
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../test/hftest/inc/hftest_impl.h:200:2: note: expanded from macro 'hftest_any_get'
        _Generic((x),                               \
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
```
734 warnings generated.
thread 'main' panicked at 'Unsupported implicit cast: NonAtomicToAtomic', /home/efenniht/.cargo/registry/src/gi
thub.com-1ecc6299db9ec823/c2rust-transpile-0.12.0/src/c_ast/conversion.rs:153:14
```

이 패닉은 가장 첫 파일 `mm_test.c` 를 처리하는 도중에 발생했습니다. 그리고 이 파일을 지우면 `main.c` 에서 또 터집니다. 일반적으로 Hafnium에 atomic variables를 사용하는 곳이 많아서, c2rust 결과를 확인하려면 Hafnium C 코드를 많이 리팩토링해야 할 것 같습니다. (자동으로 하기 위해서 손이 많이 가야 합니다 @_@)

또한 C2Rust 문서를 훑어보았는데 아직 이 정도 크기의 소프트웨어에 실제로 적용하기에는 output의 quality가 너무 별로인 것으로 보입니다. C2Rust 개발자들도 refactoring 문제를 인식하고 리팩토링 툴 또한 만들었습니다. 문제는:
 - 가능한 리팩토링은 엄청 많고 개발자의 입장에서 뭘 써야할 지 모르겠습니다.
 - 꽤 자명해 보이는 리팩토링도 사용자가 AST에 mark를 잘 달아야 합니다.

Unsafe를 줄이는 리팩토링은, `fix_unused_unsafe` 라는, 실제로는 unsafe하지 않은 코드에 대해서 unsafe를 떼어 주는 리팩토링 뿐입니다. 가능한 모든 리팩토링은 [여기](https://c2rust.com/manual/c2rust-refactor/commands.html)에 있습니다.

**Comment by jeehoonkang** [comment]
제 추측은.. 지뢰(?)들을 잘 피해가면 automatic conversion이 가능은 할 것 같다는 느낌입니다.  mm_test 해결하고, main 해결하고, ... 그 결과물이 좀 안좋을 순 있겠는데, 거기서 manual refactoring을 시작하는게 가능할지 궁금합니다.

**Comment by efenniht** [comment]
아마 잘 하면 되겠지만, 그게 의미가 있을 지 모르겠습니다.
 - 자동으로 rust로 옮기기 위해서 수작업으로 C 코드를 수정해야 합니다.
 - 그 작업이 unsafe를 줄이는 main refactoring에 별로 도움이 안 될 것 같습니다.
 - 그 작업에 대한 guide도 없고, 이 지뢰를 해결하는 게 좋은 contribution을 주지 않습니다. (대부분 c2rust의 버그보다는 구현 부족이므로)
